services:
  - type: web
    name: flask-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: HOST_NAME
        value: ${HOST_NAME}
      - key: USER_NAME
        value: ${USER_NAME}
      - key: PASSWORD
        value: ${PASSWORD}
      - key: DATABASE
        value: ${DATABASE}
      - key: HF_API_KEY
        value: ${HF_API_KEY}
    autoDeploy: true
